In [1]:
import pandas as pd
from embeds import multi_inner_align, standardize
from sklearn.decomposition import PCA
import sys
sys.path.append('..')
from rca.rca import run_rca

## Load LLM embeddings

In [2]:
fastText_CommonCrawl = pd.read_csv('../../data/embeds/fastText_CommonCrawl.csv', index_col=0)

# Llama 3 8B
Llama_3_8B_0 = pd.read_csv('../../data/llms/Llama-3.1-8B_0.csv', index_col=0)
Llama_3_8B_1 = pd.read_csv('../../data/llms/Llama-3.1-8B_1.csv', index_col=0)
Llama_3_8B_2 = pd.read_csv('../../data/llms/Llama-3.1-8B_2.csv', index_col=0)
Llama_3_8B_012 = sum(multi_inner_align([Llama_3_8B_0, Llama_3_8B_1, Llama_3_8B_2])) / 3 # ensemble approach
Llama_3_8B_12 = sum(multi_inner_align([Llama_3_8B_1, Llama_3_8B_2])) / 2

# BERT large
BERT_large_0 = pd.read_csv('../../data/llms/bert-large-uncased_0.csv', index_col=0)
BERT_large_1 = pd.read_csv('../../data/llms/bert-large-uncased_1.csv', index_col=0)
BERT_large_2 = pd.read_csv('../../data/llms/bert-large-uncased_2.csv', index_col=0)
BERT_large_012 = sum(multi_inner_align([BERT_large_0, BERT_large_1, BERT_large_2])) / 3 # ensemble approach
BERT_large_12 = sum(multi_inner_align([BERT_large_1, BERT_large_2])) / 2

# Comparing
to_compare = {
    'fastText_CommonCrawl': fastText_CommonCrawl,

    'Llama_3_8B_0': Llama_3_8B_0,
    'Llama_3_8B_1': Llama_3_8B_1,
    'Llama_3_8B_2': Llama_3_8B_2,
    'Llama_3_8B_012': Llama_3_8B_012,
    'Llama_3_8B_12': Llama_3_8B_12,

    'BERT_large_0': BERT_large_0,
    'BERT_large_1': BERT_large_1,
    'BERT_large_2': BERT_large_2,
    'BERT_large_012': BERT_large_012,
    'BERT_large_12': BERT_large_12
}

In [3]:
# Aligning for fair comparison
to_compare = dict(zip(to_compare.keys(), multi_inner_align(to_compare.values())))

# Standardizing
to_compare = {name: standardize(embed) for name, embed in to_compare.items()}
{name: embed.shape for name, embed in to_compare.items()}

{'fastText_CommonCrawl': (44450, 300),
 'Llama_3_8B_0': (44450, 4096),
 'Llama_3_8B_1': (44450, 4096),
 'Llama_3_8B_2': (44450, 4096),
 'Llama_3_8B_012': (44450, 4096),
 'Llama_3_8B_12': (44450, 4096),
 'BERT_large_0': (44450, 1024),
 'BERT_large_1': (44450, 1024),
 'BERT_large_2': (44450, 1024),
 'BERT_large_012': (44450, 1024),
 'BERT_large_12': (44450, 1024)}

## Compare

In [5]:
# Loading norm data
norms = pd.read_csv('../../data/psychNorms/psychNorms_processed.zip', index_col=0, low_memory=False, compression='zip')
norms_meta = pd.read_csv('../../data/psychNorms/psychNorms_metadata_processed.csv', index_col='norm')

# Subsetting to glasgow
norms = norms[[norm for norm in norms if 'glasgow' in norm]]

# Running tests
results = run_rca(to_compare, norms, norms_meta, n_jobs=5)
results.to_csv('../../data/results/supplement/llms.csv', index=False)
results

  0%|          | 0/13 [00:00<?, ?it/s]

fastText_CommonCrawl:   0%|          | 0/9 [00:00<?, ?it/s]

Llama_3_8B_0:   0%|          | 0/9 [00:00<?, ?it/s]

Llama_3_8B_1:   0%|          | 0/9 [00:00<?, ?it/s]

Llama_3_8B_2:   0%|          | 0/9 [00:00<?, ?it/s]

Llama_3_8B_012:   0%|          | 0/9 [00:00<?, ?it/s]

Llama_3_8B_12:   0%|          | 0/9 [00:00<?, ?it/s]

BERT_large_0:   0%|          | 0/9 [00:00<?, ?it/s]

BERT_large_1:   0%|          | 0/9 [00:00<?, ?it/s]

BERT_large_2:   0%|          | 0/9 [00:00<?, ?it/s]

BERT_large_012:   0%|          | 0/9 [00:00<?, ?it/s]

BERT_large_12:   0%|          | 0/9 [00:00<?, ?it/s]

Llama_3_8B_12_pca:   0%|          | 0/9 [00:00<?, ?it/s]

BERT_large_12_pca:   0%|          | 0/9 [00:00<?, ?it/s]

,embed,embed_type,norm,train_n,test_n,p,r2_mean,r2_sd,check
0,fastText_CommonCrawl,None,familiarity_glasgow,3705,927,300,0.664903,0.019769,pass
1,fastText_CommonCrawl,None,aoa_glasgow,3705,927,300,0.744070,0.018202,pass
2,fastText_CommonCrawl,None,concreteness_glasgow,3705,927,300,0.806406,0.010490,pass
3,fastText_CommonCrawl,None,imageability_glasgow,3705,927,300,0.751500,0.011450,pass
4,fastText_CommonCrawl,None,semantic_size_glasgow,3705,927,300,0.661660,0.011675,pass
...,...,...,...,...,...,...,...,...,...
112,BERT_large_12_pca,None,semantic_size_glasgow,3705,927,300,0.668752,0.013773,pass
113,BERT_large_12_pca,None,gender_association_glasgow,3705,927,300,0.607926,0.039202,pass
114,BERT_large_12_pca,None,valence_glasgow,3705,927,300,0.742690,0.022004,pass
115,BERT_large_12_pca,None,arousal_glasgow,3705,927,300,0.555859,0.033169,pass
116,BERT_large_12_pca,None,dominance_glasgow,3705,927,300,0.554849,0.028245,pass

In [6]:
resuls_piv = results[['embed', 'norm', 'r2_mean']].pivot(index='norm', columns='embed', values='r2_mean')
resuls_piv

embed,BERT_large_0,BERT_large_012,BERT_large_1,BERT_large_12,BERT_large_12_pca,BERT_large_2,Llama_3_8B_0,Llama_3_8B_012,Llama_3_8B_1,Llama_3_8B_12,Llama_3_8B_12_pca,Llama_3_8B_2,fastText_CommonCrawl
norm,,,,,,,,,,,,,
aoa_glasgow,0.544505,0.674546,0.673347,0.675675,0.648952,0.608934,0.592659,0.691481,0.692026,0.689229,0.655694,0.660116,0.744070
arousal_glasgow,0.444214,0.588630,0.585532,0.587701,0.555859,0.527152,0.468764,0.580573,0.566248,0.586791,0.531456,0.574990,0.569323
concreteness_glasgow,0.693819,0.812260,0.818624,0.814668,0.799491,0.765055,0.728785,0.817338,0.809845,0.816883,0.798084,0.806623,0.806406
dominance_glasgow,0.397344,0.572958,0.572923,0.579053,0.554849,0.515479,0.431336,0.543795,0.532983,0.547532,0.498874,0.534448,0.532936
familiarity_glasgow,0.462700,0.554534,0.551531,0.551068,0.531887,0.503782,0.501898,0.591983,0.587842,0.594458,0.556980,0.564877,0.664903
gender_association_glasgow,0.462572,0.618029,0.638930,0.622435,0.607926,0.530669,0.482646,0.605429,0.573724,0.608411,0.567611,0.598233,0.666486
imageability_glasgow,0.634103,0.761864,0.766894,0.764887,0.746842,0.708047,0.674631,0.759873,0.749760,0.760858,0.733903,0.750107,0.751500
semantic_size_glasgow,0.554692,0.687041,0.692673,0.694265,0.668752,0.630229,0.596764,0.698210,0.686057,0.699572,0.663444,0.689008,0.661660
valence_glasgow,0.550414,0.749975,0.761208,0.762466,0.742690,0.694481,0.593209,0.736481,0.711922,0.740695,0.712439,0.733508,0.729247

In [7]:
# Finding the top-performing
sorted_overall = resuls_piv.mean().sort_values(ascending=False)
sorted_overall

embed
fastText_CommonCrawl    0.680726
BERT_large_1            0.673518
BERT_large_12           0.672469
Llama_3_8B_12           0.671603
Llama_3_8B_012          0.669463
BERT_large_012          0.668871
Llama_3_8B_2            0.656879
Llama_3_8B_1            0.656712
BERT_large_12_pca       0.650805
Llama_3_8B_12_pca       0.635387
BERT_large_2            0.609314
Llama_3_8B_0            0.563410
BERT_large_0            0.527151
dtype: float64

## Dimensionality reduction

In [3]:
# Taking the best template combo
Llama_3_8B = Llama_3_8B_12.copy()
BERT_large = BERT_large_12.copy()

# PCAed versions
pca = PCA(n_components=300, random_state=42)  # reduce to capture 90% of original variance
Llama_3_8B_pca = pd.DataFrame(pca.fit_transform(Llama_3_8B), index=Llama_3_8B.index)
BERT_large_pca = pd.DataFrame(pca.fit_transform(X=BERT_large), index=BERT_large.index)

# feature selection
def feature_selector(embed):
    top_features = embed.std().sort_values(ascending=False).index[:300]
    return embed[top_features]

Llama_3_8B_fs = feature_selector(Llama_3_8B)
BERT_large_fs = feature_selector(BERT_large)

# Adding to comparison dict
to_compare = {
    'Llama_3_8B': Llama_3_8B,
    'BERT_large': BERT_large,
    'Llama_3_8B_pca': Llama_3_8B_pca,
    'BERT_large_pca': BERT_large_pca,
    'Llama_3_8B_fs': Llama_3_8B_fs,
    'BERT_large_fs': BERT_large_fs,
}

# Aligning for fair comparison
to_compare = dict(zip(to_compare.keys(), multi_inner_align(to_compare.values())))

# Standardizing
to_compare = {name: standardize(embed) for name, embed in to_compare.items()}
{name: embed.shape for name, embed in to_compare.items()}

{'Llama_3_8B': (46246, 4096),
 'BERT_large': (46246, 1024),
 'Llama_3_8B_pca': (46246, 300),
 'BERT_large_pca': (46246, 300),
 'Llama_3_8B_fs': (46246, 300),
 'BERT_large_fs': (46246, 300)}

In [10]:
results = run_rca(to_compare, norms, norms_meta, n_jobs=5)
results

  0%|          | 0/6 [00:00<?, ?it/s]

Llama_3_8B:   0%|          | 0/9 [00:00<?, ?it/s]

BERT_large:   0%|          | 0/9 [00:00<?, ?it/s]

Llama_3_8B_pca:   0%|          | 0/9 [00:00<?, ?it/s]

BERT_large_pca:   0%|          | 0/9 [00:00<?, ?it/s]

Llama_3_8B_fs:   0%|          | 0/9 [00:00<?, ?it/s]

BERT_large_fs:   0%|          | 0/9 [00:00<?, ?it/s]

,embed,embed_type,norm,train_n,test_n,p,r2_mean,r2_sd,check
0,Llama_3_8B,None,familiarity_glasgow,3705,927,4096,0.594680,0.010211,pass
1,Llama_3_8B,None,aoa_glasgow,3705,927,4096,0.689358,0.017217,pass
2,Llama_3_8B,None,concreteness_glasgow,3705,927,4096,0.816984,0.012927,pass
3,Llama_3_8B,None,imageability_glasgow,3705,927,4096,0.760976,0.016631,pass
4,Llama_3_8B,None,semantic_size_glasgow,3705,927,4096,0.703889,0.013483,pass
5,Llama_3_8B,None,gender_association_glasgow,3705,927,4096,0.608848,0.020154,pass
6,Llama_3_8B,None,valence_glasgow,3705,927,4096,0.740910,0.011563,pass
7,Llama_3_8B,None,arousal_glasgow,3705,927,4096,0.587140,0.012080,pass
8,Llama_3_8B,None,dominance_glasgow,3705,927,4096,0.547829,0.013118,pass
9,BERT_large,None,familiarity_glasgow,3705,927,1024,0.551065,0.026225,pass
10,BERT_large,None,aoa_glasgow,3705,927,1024,0.675682,0.009814,pass
11,BERT_large,None,concreteness_glasgow,3705,927,1024,0.814668,0.012088,pass
12,BERT_large,None,imageability_glasgow,3705,927,1024,0.764889,0.013052,pass
13,BERT_large,None,semantic_size_glasgow,3705,927,1024,0.694275,0.007036,pass
14,BERT_large,None,gender_association_glasgow,3705,927,1024,0.622442,0.037708,pass
15,BERT_large,None,valence_glasgow,3705,927,1024,0.762475,0.018974,pass
16,BERT_large,None,arousal_glasgow,3705,927,1024,0.587701,0.030418,pass
17,BERT_large,None,dominance_glasgow,3705,927,1024,0.579064,0.025892,pass
18,Llama_3_8B_pca,None,familiarity_glasgow,3705,927,300,0.556941,0.014419,pass
19,Llama_3_8B_pca,None,aoa_glasgow,3705,927,300,0.655669,0.012498,pass
20,Llama_3_8B_pca,None,concreteness_glasgow,3705,927,300,0.798074,0.013789,pass
21,Llama_3_8B_pca,None,imageability_glasgow,3705,927,300,0.733886,0.019696,pass
22,Llama_3_8B_pca,None,semantic_size_glasgow,3705,927,300,0.663421,0.021710,pass
23,Llama_3_8B_pca,None,gender_association_glasgow,3705,927,300,0.567576,0.021392,pass
24,Llama_3_8B_pca,None,valence_glasgow,3705,927,300,0.712433,0.021903,pass
25,Llama_3_8B_pca,None,arousal_glasgow,3705,927,300,0.531417,0.028018,pass
26,Llama_3_8B_pca,None,dominance_glasgow,3705,927,300,0.498839,0.012241,pass
27,BERT_large_pca,None,familiarity_glasgow,3705,927,300,0.531883,0.025008,pass
28,BERT_large_pca,None,aoa_glasgow,3705,927,300,0.648934,0.008008,pass
29,BERT_large_pca,None,concreteness_glasgow,3705,927,300,0.799490,0.014272,pass
30,BERT_large_pca,None,imageability_glasgow,3705,927,300,0.746840,0.014755,pass
31,BERT_large_pca,None,semantic_size_glasgow,3705,927,300,0.668740,0.013775,pass
32,BERT_large_pca,None,gender_association_glasgow,3705,927,300,0.607918,0.039209,pass
33,BERT_large_pca,None,valence_glasgow,3705,927,300,0.742684,0.022009,pass
34,BERT_large_pca,None,arousal_glasgow,3705,927,300,0.555847,0.033175,pass
35,BERT_large_pca,None,dominance_glasgow,3705,927,300,0.554841,0.028251,pass
36,Llama_3_8B_fs,None,familiarity_glasgow,3705,927,300,0.467467,0.009289,pass
37,Llama_3_8B_fs,None,aoa_glasgow,3705,927,300,0.548604,0.019943,pass
38,Llama_3_8B_fs,None,concreteness_glasgow,3705,927,300,0.743909,0.019137,pass
39,Llama_3_8B_fs,None,imageability_glasgow,3705,927,300,0.687782,0.022629,pass
40,Llama_3_8B_fs,None,semantic_size_glasgow,3705,927,300,0.573047,0.021273,pass
41,Llama_3_8B_fs,None,gender_association_glasgow,3705,927,300,0.410395,0.043059,pass
42,Llama_3_8B_fs,None,valence_glasgow,3705,927,300,0.589510,0.029872,pass
43,Llama_3_8B_fs,None,arousal_glasgow,3705,927,300,0.401842,0.034089,pass
44,Llama_3_8B_fs,None,dominance_glasgow,3705,927,300,0.393418,0.038700,pass
45,BERT_large_fs,None,familiarity_glasgow,3705,927,300,0.504675,0.021482,pass
46,BERT_large_fs,None,aoa_glasgow,3705,927,300,0.602322,0.010396,pass
47,BERT_large_fs,None,concreteness_glasgow,3705,927,300,0.775483,0.019586,pass
48,BERT_large_fs,None,imageability_glasgow,3705,927,300,0.723488,0.021420,pass
49,BERT_large_fs,None,semantic_size_glasgow,3705,927,300,0.627879,0.015092,pass
50,BERT_large_fs,None,gender_association_glasgow,3705,927,300,0.560255,0.037016,pass
51,BERT_large_fs,None,valence_glasgow,3705,927,300,0.674259,0.025784,pass
52,BERT_large_fs,None,arousal_glasgow,3705,927,300,0.521045,0.029500,pass
53,BERT_large_fs,None,dominance_glasgow,3705,927,300,0.503620,0.032182,pass

In [11]:
resuls_piv = results[['embed', 'norm', 'r2_mean']].pivot(index='norm', columns='embed', values='r2_mean')
sorted_overall = resuls_piv.mean().sort_values(ascending=False)
sorted_overall

embed
BERT_large        0.672474
Llama_3_8B        0.672290
BERT_large_pca    0.650797
Llama_3_8B_pca    0.635362
BERT_large_fs     0.610336
Llama_3_8B_fs     0.535108
dtype: float64

In [4]:
## Saving
Llama_3_8B.to_csv('../../data/embeds/Llama_3_8B.csv')
BERT_large.to_csv('../../data/embeds/BERT_large.csv')
Llama_3_8B_pca.to_csv('../../data/embeds/Llama_3_8B_pca.csv')
BERT_large_pca.to_csv('../../data/embeds/BERT_large_pca.csv')