In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import RidgeCV, LogisticRegressionCV
from sklearn.model_selection import StratifiedKFold, cross_val_score
from tqdm.notebook import tqdm
import json
from rca import  make_multiclass_scoring, make_binary_scoring, process_categorical, best_logistic_solver, checker
import pickle
import os

## Loading Data

In [2]:
# Loading rca results
rca_results_dir = '../../data/results/rca/'
rcas = [pd.read_csv(rca_results_dir + f_name) for f_name in os.listdir(rca_results_dir) if f_name.endswith('.csv')]
rca = pd.concat(rcas, ignore_index=True)

# Loading norm data
meta = pd.read_csv('../../data/psychNorms/psychNorms_metadata_processed.csv', index_col=0)
norms = pd.read_csv('../../data/psychNorms/psychNorms_processed.zip', index_col=0, compression='zip', low_memory=False)

# Adding norm_cat to rca
rca['norm_cat'] = (
    rca['norm']
    .apply(lambda norm: meta.loc[norm]['category'])
    .replace({'_': ' '}, regex=True)
)

rca

,embed,embed_type,norm,train_n,test_n,p,r2_mean,r2_sd,check,norm_cat
0,norms_sensorimotor,behavior,frequency_lund,21824,5456,11,0.039306,0.004500,pass,frequency
1,norms_sensorimotor,behavior,frequency_kucera,14486,3622,11,0.029403,0.007545,pass,frequency
2,norms_sensorimotor,behavior,frequency_subtlexus,23015,5754,11,0.068095,0.007467,pass,frequency
3,norms_sensorimotor,behavior,frequency_subtlexuk,23433,5859,11,0.057376,0.005951,pass,frequency
4,norms_sensorimotor,behavior,frequency_blog_gimenes,26140,6536,11,0.065925,0.002942,pass,frequency
...,...,...,...,...,...,...,...,...,...,...
7561,fMRI_text_denoise,brain,imageability_vanarsdall,69,18,128,NaN,NaN,test_n < 20,imageability
7562,fMRI_text_denoise,brain,familiarity_fear,58,15,128,NaN,NaN,test_n < 20,familiarity
7563,fMRI_text_denoise,brain,aoa_fear,58,15,128,NaN,NaN,test_n < 20,age of acquisition
7564,fMRI_text_denoise,brain,imageability_fear,58,15,128,NaN,NaN,test_n < 20,imageability
7565,fMRI_text_denoise,brain,sensory_experience_juhasz2013,447,112,128,-0.162948,0.221089,pass,sensory

In [3]:
embed_avgs = (
    rca[['embed', 'norm_cat', 'r2_mean']]
    .groupby(['embed', 'norm_cat']).median(numeric_only=True) # median is used to mitigate outliers within norm_cats
    .groupby('embed').mean()
    .rename(columns={'r2_mean': 'r2_avg'})
)
embed_avgs.sort_values(by='r2_avg', ascending=False)

                              r2_avg
embed
BERT_base                   0.521014
Llama_3_8B                  0.510892
CBOW_GoogleNews             0.447378
SVD_SWOW                    0.398496
SkipGram_SWOW               0.345978
fastText_CommonCrawl        0.327726
GloVe_CommonCrawl           0.313214
spherical_text_Wikipedia    0.308737
fastText_Wiki_News          0.308665
GloVe_Wikipedia             0.299761
GloVe_Twitter               0.296789
SVD_EAT                     0.296205
morphoNLM                   0.290614
LexVec_CommonCrawl          0.290600
SVD_SouthFlorida            0.252671
norms_sensorimotor          0.158820
THINGS                      0.151210
fastTextSub_OpenSub         0.131515
SVD_similarity_relatedness  0.040116
fMRI_speech_cognival       -0.030373
EEG_text                   -0.046948
microarray                 -0.051284
fMRI_text_cognival         -0.052246
EEG_speech                 -0.065708
fMRI_text_denoise          -0.208527
eye_tracking               -0.603227

In [4]:
# Adding embed types
with open('../../data/embed_to_dtype.json', 'r') as f:
    embed_to_type = json.load(f)
    embed_avgs['type'] = embed_avgs.index.map(embed_to_type)

# Finding top 2 text 
text_name_1, text_name_2 = (
    embed_avgs
    .query('type == "text"')
    .sort_values('r2_avg', ascending=False)
    .head(2).index.tolist()
)
text_name_1, text_name_2

('BERT_base', 'Llama_3_8B')

In [5]:
# Finding top behavior
behavior_name = (
    embed_avgs
    .query('type == "behavior"')
    .sort_values('r2_avg', ascending=False)
    .head(1).index[0]
)
behavior_name

'SVD_SWOW'

In [6]:
# Taking second-best brain because vocabulary is much larger and performance almost the same
brain_name = 'EEG_speech'
brain_name

'EEG_speech'

In [18]:
# Loading embeds
text_1 = pd.read_csv(f'../../data/embeds/{text_name_1}.csv', index_col=0)
text_2 = pd.read_csv(f'../../data/embeds/{text_name_2}.csv', index_col=0)
text_base = pd.read_csv('../../data/embeds/CBOW_GoogleNews.csv', index_col=0) # 300D text baseline (supplement)

behavior = pd.read_csv(f'../../data/embeds/{behavior_name}.csv', index_col=0)
brain = pd.read_csv(f'../../data/embeds/{brain_name}.csv', index_col=0)

with open('../../data/brain_behav_union.pkl', 'rb') as f:
    brain_behav_union = list(pickle.load(f))

# Subsdetting to brain and behavior union
text_1 = text_1.loc[text_1.index.isin(brain_behav_union)]
text_2 = text_2.loc[text_2.index.isin(brain_behav_union)]
text_base = text_base.loc[text_base.index.isin(brain_behav_union)]
behavior = behavior.loc[behavior.index.isin(brain_behav_union)]
brain = brain.loc[brain.index.isin(brain_behav_union)]

{'text_1': text_1.shape, 'text_2': text_2.shape, 'text_base': text_base.shape, 'behavior': behavior.shape, 'brain': brain.shape}

{'text_1': (9906, 768),
 'text_2': (9906, 4096),
 'text_base': (42837, 300),
 'behavior': (11783, 300),
 'brain': (1591, 130)}

In [9]:
def ensemble(embeds: list) -> pd.DataFrame:
    return pd.concat(embeds, axis=1, join='inner')

# Ensembling for text vs behavior comparison
text_behav_embeds = {
    text_name_1 + '&' + text_name_2: ensemble([text_1, text_2]),
    text_name_1 + '&' + 'CBOW_GoogleNews': ensemble([text_1, text_base]), # BERT & CBOW baseline (supplement
    text_name_1 + '&' + behavior_name: ensemble([text_1, behavior]),
    text_name_2 + '&' + behavior_name: ensemble([text_2, behavior]),
}

# Ensembling for text vs brain comparison
text_brain_embeds = {
    text_name_1 + '&' + text_name_2: ensemble([text_1, text_2]),
    text_name_1 + '&' + brain_name: ensemble([text_1, brain]),
    text_name_2 + '&' + brain_name: ensemble([text_2, brain]),
}

# Fixing column names
for comparison_dict in [text_behav_embeds, text_brain_embeds]:
    for embed_name, embed in comparison_dict.items():
        embed.columns = list(range(embed.shape[1]))

def multi_df_index_align(embed_dict) -> dict:
    """Inner-aligns the indexes of multiple dfs"""
    vocabs = [set(embed.index) for embed in embed_dict.values()]
    intersect = sorted(list(set.intersection(*vocabs)))
    return {name: df.loc[intersect] for name, df in embed_dict.items()}

# Subsetting each comparison dict to the same vocabulary
text_behav_embeds = multi_df_index_align(text_behav_embeds)
text_brain_embeds = multi_df_index_align(text_brain_embeds)

# Standardizing after aligning (on same vocabulary)
standardize = lambda df: (df - df.mean()) / df.std()
text_behav_embeds = {name: standardize(embed) for name, embed in text_behav_embeds.items()}
text_brain_embeds = {name: standardize(embed) for name, embed in text_brain_embeds.items()}

print('text vs behavior:')
print({name: embed.shape for name, embed in text_behav_embeds.items()})

print('text vs brain')
print({name: embed.shape for name, embed in text_brain_embeds.items()})

text vs behavior:
{'BERT_base&Llama_3_8B': (7315, 4864), 'BERT_base&CBOW_GoogleNews': (7315, 1068), 'BERT_base&SVD_SWOW': (7315, 1068), 'Llama_3_8B&SVD_SWOW': (7315, 4396)}
text vs brain
{'BERT_base&Llama_3_8B': (947, 4864), 'BERT_base&EEG_speech': (947, 898), 'Llama_3_8B&EEG_speech': (947, 4226)}

## Cross Validation

In [12]:
comparisons = {
    'text_brain': text_brain_embeds,
    'text_behav': text_behav_embeds,
}

# Making results directory
rca_ensemb_pth = '../../data/results/rca_ensemb/'
for comparison_name in comparisons.keys():
    os.makedirs(os.path.join(rca_ensemb_pth, comparison_name), exist_ok=True)

In [17]:
# Changing associated_embed to more usable format
meta['associated_embed'] = meta['associated_embed'].str.split(' ')

# Ridge
min_ord, max_ord = -5, 5
alphas = np.logspace(
    min_ord, max_ord, max_ord - min_ord + 1
)
ridge = RidgeCV(alphas=alphas)

# Logistic hyperparameters
Cs = 1 / alphas
inner_cv = 5
penalty = 'l2'

# Scorers
binary_scoring = make_binary_scoring()
multiclass_scoring = make_multiclass_scoring()
continuous_scoring = 'r2'

# outer_cv setting 
outer_cv, n_jobs = 5, 5

# Running comparative RCA for text-behavior and text-brain
for comparison_name, comparison_dict in comparisons.items():
    print('---------------------------')
    print(comparison_name)
    for embed_name, embed in comparison_dict.items():

        results = []
        for norm_name in tqdm(norms.columns, desc=embed_name):

            # Aligning embed with norm
            y = norms[norm_name].dropna()
            X, y = embed.align(y, axis='index', join='inner', copy=True)

            # Checking norm dtype
            norm_dtype = meta.loc[norm_name, 'type']

            # Solvers, scoring, estimators ir categorical or continuous
            if norm_dtype in ['binary', 'multiclass']: # categorical
                X, y = process_categorical(outer_cv, inner_cv, X, y)

                # may have switched form multi to bin after processing
                norm_dtype = 'binary' if len(y.unique()) == 2 else 'multiclass'

                # Cross validation settings for logistic regression
                solver = best_logistic_solver(y, norm_dtype)

                # Defining logistic regression
                estimator = LogisticRegressionCV(
                    Cs=Cs, penalty=penalty, cv=StratifiedKFold(inner_cv), solver=solver
                )
                scoring = binary_scoring if norm_dtype == 'binary' else multiclass_scoring
            else: # continuous
                estimator, scoring = ridge, continuous_scoring

            # Cross validation
            associated_embed = meta.loc[norm_name, 'associated_embed']
            check = checker(list(comparison_dict.keys()), y, norm_dtype, associated_embed, outer_cv)
            if check == 'pass':
                r2s = cross_val_score(estimator, X, y, cv=outer_cv, scoring=scoring, n_jobs=n_jobs) # stratification is automatically used for classification
            else:
                r2s = pd.Series([np.nan] * outer_cv)

            # Saving
            train_n = int(((outer_cv - 1) / outer_cv) * len(y))
            for i, r2 in enumerate(r2s):
                results.append([embed_name, norm_name, train_n, i + 1, r2, check])


        results = pd.DataFrame(results, columns=['embed', 'norm', 'train_n', 'fold', 'r2', 'check'])
        results.to_csv(f'{rca_ensemb_pth}{comparison_name}/{embed_name}.csv', index=False)

        # Printing
        print(results[['norm', 'r2']].groupby('norm').mean().sort_values(by='r2', ascending=False).head(10))
        print('--------------------------------')

---------------------------
text_brain

BERT_base&Llama_3_8B:   0%|          | 0/5 [00:00<?, ?it/s]

                              r2
norm
frequency_blog_gimenes  0.852538
frequency_lund          0.842442
frequency_subtlexus     0.838298
frequency_subtlexuk     0.806542
frequency_kucera        0.791907
--------------------------------

BERT_base&EEG_speech:   0%|          | 0/5 [00:00<?, ?it/s]

                              r2
norm
frequency_blog_gimenes  0.848046
frequency_lund          0.845159
frequency_subtlexus     0.833056
frequency_kucera        0.802903
frequency_subtlexuk     0.798522
--------------------------------

Llama_3_8B&EEG_speech:   0%|          | 0/5 [00:00<?, ?it/s]

KeyboardInterrupt: